/* Home auto-generated by npm run generator */
import { RouteComponentProps } from "@reach/router"
import { Theme } from "@material-ui/core"
import { makeStyles, CSSProperties } from "@material-ui/styles"
import { observer } from "mobx-react"
import React from "react"
import { useRootClasses } from "style"
import clsx from "clsx"

interface HomeProps extends RouteComponentProps {

}

const useStyles = makeStyles((theme: Theme) => ({
    homePage: {
        backgroundColor: "transparent"
    } as CSSProperties
}))

const Home: React.FC<React.PropsWithChildren<HomeProps>> = (props: React.PropsWithChildren<HomeProps>) => {
    const classes = useStyles();
    const rootClasses = useRootClasses();

    return (
        <div className={classes.homePage}>
            <h2 className={clsx(rootClasses.textCenter)}>Home Page</h2>
            {props.children}
        </div>
    )
}

export default observer(Home)